server.port=8888

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.application.name=SSA2.0-RAGPLUS

#  config
spring.ai.dashscope.api-key=sk-feb9bd5742e14c9f95370ab34e426d33
# ???????
spring.ai.dashscope.agent.options.app-id=07e51894e0af48079c82857746fb756c