spring.application.name=springAi-demo

server.port=8080


spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.api-key=sk-5dc71be51fb84bf3b6325b545e7b6514
spring.ai.deepseek.model=deepseek-chat

# ??0-2?? 0??????? 2????????
spring.ai.deepseek.chat.options.temperature=0.7
