server.port=10086
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.application.name=SSA-helloWorld

#  config
spring.ai.dashscope.api-key=sk-feb9bd5742e14c9f95370ab34e426d33
#spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
#spring.ai.dashscope.chat.options.model=deepseek-r1

spring.data.redis.host=lb-test-lan.beeselect.net
spring.data.redis.port=6379
spring.data.redis.password=password@SCM!2020
spring.data.redis.database=0
spring.data.redis.timeout=5000

spring.ai.chat.memory.redis.key-prefix=ai:chat:memory:
